name: 'GitHub Action for Deploy'
description: 'Build docker image'
inputs:
  target:
    description: 'specify which target to deploy to'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}
branding:
  icon: 'play'
  color: 'green'